package io.github.mirkoscotti.nio.s3.operations;

import java.net.URI;

/**
 * Base builder for creating {@link AwsConnector} instances backed by one of the AWS clients.
 * <p>
 * This class implements the common configuration steps shared by all AWS service connectors:
 * endpoint override, region, and credentials. Concrete subclasses are responsible for wiring each
 * setting into the specific SDK client builder they wrap, and for providing the factory function
 * that turns the built client into the corresponding connector.
 *
 * @param <A>
 *            the concrete self-referential builder type
 * @param <B>
 *            the AWS SDK client builder being configured
 * @param <C>
 *            the connector subtype this builder produces
 * @param <W>
 *            the client generated by the SDK builder
 * @author mirko.scotti
 * @version Dec 13, 2025
 */
interface ConnectorBuilder<B extends ConnectorBuilder<B, T>, T>
{

	/**
	 * Overrides the default AWS service endpoint with the given URI. This typically occurs during
	 * tests when possibly Localstack is accessed instead of AWS.
	 *
	 * @param endpoint
	 *            the custom endpoint URI
	 * @return this builder
	 */
	B withEndpoint(URI endpoint);

	/**
	 * Overrides the AWS region for the service client. Default is <code>us-east-1</code>
	 *
	 * @param region
	 *            the AWS region identifier
	 * @return this builder instance for fluent chaining
	 */
	B withRegion(String region);

	/**
	 * Static AWS client credentials configuration.
	 *
	 * @param accessKey
	 *            the AWS access key identifier
	 * @param secretKey
	 *            the AWS secret access key
	 * @return this builder
	 */
	B withCredentials(String accessKey, String secretKey);

	/**
	 * Creates an instance of the connector according to the <code>with</code> methods
	 * configuration.
	 *
	 * @return the connector instance
	 */
	T build();
}
