name: Create Pull Request

on:
  push:
    branches-ignore:
      - main
        
permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write
  
jobs:

  create-pull-request:
    runs-on: ubuntu-latest
    
    env:
      BASE_DIRECTORY: .github/scripts/pull-request-trigger
    
    steps:
          
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Issue Number
        id: issue_extractor
        env:
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: bash ${BASE_DIRECTORY}/extract-issue.sh
          
      - name: Check Pull Request
        id: pull_request_checker
        if: steps.issue_extractor.outputs.issue_number > 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: bash ${BASE_DIRECTORY}/check-pull-request.sh
          
      - name: Issue Details
        id: issue_details
        if: steps.pull_request_checker.outputs.pull_request_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.issue_extractor.outputs.issue_number }}
        run: bash ${BASE_DIRECTORY}/issue-details.sh
          
      - name: Base Branch
        id: base_branch
        if: steps.pull_request_checker.outputs.pull_request_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ steps.issue_extractor.outputs.issue_number }}
        run: bash ${BASE_DIRECTORY}/base-branch.sh
          
      - name: Create Pull Request
        id: pull_request_creator
        if: steps.pull_request_checker.outputs.pull_request_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.issue_extractor.outputs.issue_number }}
          ISSUE_DETAILS: ${{ steps.issue_details.outputs.issue_body }}
          ISSUE_USER: ${{ steps.issue_details.outputs.issue_user }}
          ISSUE_URL: ${{ steps.issue_details.outputs.issue_url }}
          ISSUE_TITLE: ${{ steps.issue_details.outputs.issue_title }}
          BRANCH_NAME: ${{ github.ref_name }}
          BASE_BRANCH: ${{ steps.base_branch.outputs.name }}
        run: bash ${BASE_DIRECTORY}/create-pull-request.sh
                    
      - name: Final Comment
        if: steps.pull_request_checker.outputs.pull_request_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.issue_extractor.outputs.issue_number }}
          BRANCH_NAME: ${{ github.ref_name }}
          BASE_BRANCH: ${{ steps.base_branch.outputs.name }}
          PULL_REQUEST_URL: ${{ steps.pull_request_creator.outputs.url }}
        run: bash ${BASE_DIRECTORY}/comment-pull-request.sh